import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/core/provider";
import Navbar from "@/components/spandana/navbar";
import Footer from "@/components/spandana/footer";

// import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientId = process.env.GOOGLE_CLIENT_ID || "";
  console.log(clientId);
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <GoogleOAuthProvider clientId={clientId}> */}
          <Navbar />
          <main>{children}</main>
          <Footer />
          {/* </GoogleOAuthProvider> */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
